/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface ImageUploadButton {
    }
    interface ImageUploadCard {
    }
    interface ImageUploadDropzone {
        "caption": string;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLImageUploadButtonElement extends Components.ImageUploadButton, HTMLStencilElement {
    }
    var HTMLImageUploadButtonElement: {
        prototype: HTMLImageUploadButtonElement;
        new (): HTMLImageUploadButtonElement;
    };
    interface HTMLImageUploadCardElement extends Components.ImageUploadCard, HTMLStencilElement {
    }
    var HTMLImageUploadCardElement: {
        prototype: HTMLImageUploadCardElement;
        new (): HTMLImageUploadCardElement;
    };
    interface HTMLImageUploadDropzoneElement extends Components.ImageUploadDropzone, HTMLStencilElement {
    }
    var HTMLImageUploadDropzoneElement: {
        prototype: HTMLImageUploadDropzoneElement;
        new (): HTMLImageUploadDropzoneElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "image-upload-button": HTMLImageUploadButtonElement;
        "image-upload-card": HTMLImageUploadCardElement;
        "image-upload-dropzone": HTMLImageUploadDropzoneElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface ImageUploadButton {
        "onButtonClicked"?: (event: CustomEvent<void>) => void;
    }
    interface ImageUploadCard {
    }
    interface ImageUploadDropzone {
        "caption"?: string;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-root": AppRoot;
        "image-upload-button": ImageUploadButton;
        "image-upload-card": ImageUploadCard;
        "image-upload-dropzone": ImageUploadDropzone;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "image-upload-button": LocalJSX.ImageUploadButton & JSXBase.HTMLAttributes<HTMLImageUploadButtonElement>;
            "image-upload-card": LocalJSX.ImageUploadCard & JSXBase.HTMLAttributes<HTMLImageUploadCardElement>;
            "image-upload-dropzone": LocalJSX.ImageUploadDropzone & JSXBase.HTMLAttributes<HTMLImageUploadDropzoneElement>;
        }
    }
}
